name: Print Date and Time

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-date-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print date and time
        run: |
          echo "Current Date and Time: $(date)"
